version: "3.0"
services:
  back-end:
    build: ./application/
    container_name: application
    ports:
      - "8080:8080"
    depends_on:
      - database
    env_file:
      - 'db.env'
      
  database:
    image: postgres:14-alpine
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - 'db.env'

volumes:
  volumes: